# stat blocks for mech classes

MECH_TANK_HP = 15
MECH_TANK_ATK = 2
MECH_TANK_SPD = 1

MECH_GUNNER_HP = 12
MECH_GUNNER_ATK = 1
MECH_GUNNER_SPD = 3

MECH_BOMBER_HP = 10
MECH_BOMBER_ATK = 3
MECH_BOMBER_SPD = 2

MECH_SCOUT_HP = 8
MECH_SCOUT_ATK = 1
MECH_SCOUT_SPD = 1

MECH_SOLIDER_HP = 10
MECH_SOLIDER_ATK = 1.5
MECH_SOLIDER_SPD = 1

MECH_LIEUTENANT_HP = 12
MECH_LIEUTENANT_ATK = 2
MECH_LIEUTENANT_SPD = 1.5

MECH_CAPTAIN_HP = 15
MECH_CAPTAIN_ATK = 2
MECH_CAPTAIN_SPD = 2

MECH_COMMANDER_HP = 18
MECH_COMMANDER_ATK = 2
MECH_COMMANDER_SPD = 2

MECH_GENERAL_HP = 20
MECH_GENERAL_ATK = 3
MECH_GENERAL_SPD = 3

STARTING_DECK = 10
STARTING_SHOOT_CARDS = 6
STARTING_SHIELD_CARDS = 2 
STARTING_REPAIR_CARDS = 2
START_HAND_SIZE = 3 